# Generated by Django 4.2.3 on 2023-07-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priortiy',
            new_name='priority',
        ),
    ]
